### ISSUE TITLE
More support for other unique characters?

### ISSUE THREAD

**Issue by SalbugVR** [cyberkitsune/vrc-osc-scripts#1]
Are there plans to get other unique language characters supported as well other then Japanese? Other characters like **Ü** and **Ø** for example get filtered as **?** as well.

![image](https://user-images.githubusercontent.com/24326270/187318198-00ce62a4-56fb-4777-90cd-856489013471.png)

**Comment by cyberkitsune** [comment]
I'll have to take a look at what to do about this; There may be a library to map characters to similar-_ish_ ascii, and if so I'll consider adding it in.

Ultimately I'd like VRChat to just support some kind of utf-8 / unicode support in Chatbox OSC, (I've suggested it to them at https://github.com/vrchat-community/osc/issues/137)

Will investigate, but may become blocked on proper VRC utf-8 / unicode support.
