### ISSUE TITLE
Refresh rate of VRCNowPlaying in VRC.

### ISSUE THREAD

**Issue by UwUo-oUwU** [cyberkitsune/vrc-osc-scripts#4]
The timestamp of the song playing seems to only update every 4.5 or so seconds.

**Comment by senkodev** [comment]
That most likely was made by design - just to avoid the rate limits

**Comment by cyberkitsune** [comment]
the timestamp not updating is not due to the delay to avoid the VRC ratelimit, it's more due to the Windows API I'm using not updating the timestamp. Sadly not sure how much I can do about it xwx
