### ISSUE TITLE
song_position wont show

### ISSUE THREAD

**Issue by Progamer75303** [cyberkitsune/vrc-osc-scripts#8]
the song_position is always at 0:00

**Comment by cyberkitsune** [comment]
What application are you using to play media? It may be due to the app not reporting to the windows API correctly.

**Comment by Progamer75303** [comment]
> What application are you using to play media? It may be due to the app not reporting to the windows API correctly.
Groove-Music on windows 10

**Comment by cyberkitsune** [comment]
for applications where it throws out the initial timestamp and doesn't update it, I think I'll be adding some logic to try and make VRCNowPlaying guess the correct timestamp soon!

**Comment by KuryKat** [comment]
~~Oh my I saw the comment as it was posted that's the first time it happens to me~~
